# Generated by Django 4.2.16 on 2024-11-13 15:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_relationship_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sports', '스포츠'), ('travel', '여행'), ('cook', '요리'), ('food', '맛집탐방'), ('fashion', '패션'), ('books', '독서'), ('music', '음악'), ('friends', '사교'), ('etc', '이외')], max_length=100, null=True),
        ),
    ]
