# Generated by Django 4.2.16 on 2024-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_hashtag_alter_post_content_post_tags'),
        ('account', '0007_alter_user_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='board.post', verbose_name='좋아요 누른 Post목록'),
        ),
    ]
